export const SubscriptionPlans = {
  basic: {
    name: "basic",
    description: "Perfect for small teams starting out",
    priceMonthly: 10,
    priceAnnual: 100,
    stripePriceIdMonthly: process.env.STRIPE_BASIC_MONTHLY_PRICE_ID,
    stripePriceIdAnnual: process.env.STRIPE_BASIC_ANNUAL_PRICE_ID,
    limits: {
      jobPostings: 5,
      featuredListings: 0,
    },
    allowedRoles: ["APPLICANT_MANAGER"],
    features: ["5 job postings", "Applicant management", "Basic analytics"],
  },
  growth: {
    name: "growth",
    description: "For growing companies",
    priceMonthly: 25,
    priceAnnual: 200,
    stripePriceIdMonthly: process.env.STRIPE_GROWTH_MONTHLY_PRICE_ID,
    stripePriceIdAnnual: process.env.STRIPE_GROWTH_ANNUAL_PRICE_ID,
    limits: {
      jobPostings: 10,
      featuredListings: 3,
    },
    allowedRoles: ["APPLICANT_MANAGER", "JOB_LISTING_MANAGER"],
    features: [
      "10 job postings",
      "3 featured listings",
      "Advanced applicant management",
      "Job listing management",
    ],
  },
  enterprise: {
    name: "enterprise",
    description: "For large organizations",
    priceMonthly: 100,
    priceAnnual: 1000,
    stripePriceIdMonthly: process.env.STRIPE_ENTERPRISE_MONTHLY_PRICE_ID,
    stripePriceIdAnnual: process.env.STRIPE_ENTERPRISE_ANNUAL_PRICE_ID,
    limits: {
      jobPostings: 15,
      featuredListings: Infinity,
    },
    allowedRoles: [
      "OWNER",
      "ORG_ADMIN",
      "APPLICANT_MANAGER",
      "JOB_LISTING_MANAGER",
    ],
    features: [
      "15 job postings",
      "Unlimited featured listings",
      "Full team management",
      "Priority support",
      "Custom integrations",
    ],
  },
} as const;
